### ISSUE TITLE
No hard URL

### ISSUE THREAD

**Issue by jeroenpijpker** [TomiEckert/ProjectRoboArm#2]
Don't use hard URL like xhttp1.open("GET", "http://192.168.0.10:8181/set_servo1?speed=" + 
  slider1.value, true); xhttp1.send();

**Comment by TomiEckert** [comment]
Possible solution:
- Get the local ip in the python script with the "hostname -i" command.
- Pass it to the website with flask.

**Comment by TomiEckert** [comment]
Fixed in [#9a2b1d73](https://github.com/TomiEckert/ProjectRoboArm/commit/9a2b1d738ba3aee437d1e4c9c96ce66aec19cd8d)
